# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "lootr"
type = "required"
versionRange = "[0.10,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "artifacts"
type = "optional"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
